export const WALLET_LIST_REQUEST = 'WALLET_LIST_REQUEST'
export const WALLET_LIST_SUCCESS = 'WALLET_LIST_SUCCESS' 
export const WALLET_LIST_FAIL = 'WALLET_LIST_FAIL'

export const WALLET_DETAILS_REQUEST = 'WALLET_DETAILS_REQUEST'
export const WALLET_DETAILS_SUCCESS = 'WALLET_DETAILS_SUCCESS' 
export const WALLET_DETAILS_FAIL = 'WALLET_DETAILS_FAIL'

export const WALLET_ADD_IDLE = 'WALLET_ADD_IDLE' 
export const WALLET_ADD_REQUEST = 'WALLET_ADD_REQUEST'
export const WALLET_ADD_SUCCESS = 'WALLET_ADD_SUCCESS' 
export const WALLET_ADD_FAIL = 'WALLET_ADD_FAIL'
